language: python
python: "3.6"
env:
  global:
    - SPARK_HOME=spark-2.3.1-bin-hadoop2.7
install:
  - pip install -r requirements.txt
  - |
    if [ ! -f "$SPARK_HOME/bin/spark-submit" ]; then
      wget http://www-us.apache.org/dist/spark/spark-2.3.1/spark-2.3.1-bin-hadoop2.7.tgz
      tar xf spark-2.3.1-bin-hadoop2.7.tgz
    else
      echo "Found existing Spark"
    fi
script:
  - black --check *.py
  - pytest test_convert.py test_dask.py test_scanpy_zap.py test_show_meta.py
cache:
  directories:
    - spark-2.3.1-bin-hadoop2.7
    - /home/travis/virtualenv/python3.6.3/bin
